/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() { //Esto no mola, deberías hacerlo de otra forma
        //Yahooooooooooo
        return true;
    }
}
